kreait_firebase:
  projects:
    my_project:
      # Remove/Override the following line if running on GCE
      credentials: '%env(FIREBASE_CREDENTIALS)%'
      # database_uri: 'https://my-project-default-rtdb.firebaseio.com'
      # or, depending on your Firebase project configuration
      # database_uri: 'https://my-project-default-rtdb.europe-west1.firebasedatabase.app'
      verifier_cache: cache.app
      auth_token_cache: cache.app
